@Library('pcloud-jenkins-library') _
pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:4.6-1.2'
            args '-v /etc/resolv.conf:/etc/resolv.conf'
            label 'jump-vpc-x86_64'
        }
    }
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
        OS_USERNAME = credentials('OS_USERNAME')
        OS_PASSWORD = credentials('OS_PASSWORD')
        PULL_SECRET = credentials('PULL_SECRET')
        URL_SCNLCICDCLOUD=credentials('URL_SCNLCICDCLOUD')
        URL_SCNLPOWERCLOUD=credentials('URL_SCNLPOWERCLOUD')

        VIR_CHOSE = "PowerVM"
        HARDWARE_CHOSE = "P9"
        NODE_OS = "rhcos-44"
        BASTION_OS  = "RHEL8.0"
        TIMEOUT = "0"
        RELEASE="4.4"

        FUNCTIONAL_TEST_REPO = "icp-sanity-bats"
        TERRAFORM_VER = "0.11.13"
        TEST_SUITE = "ppc64le-edge"
        OS = "linux"
        OS_IDENTITY_API_VERSION='3'
        OS_TENANT_NAME="ibm-default"
        OS_USER_DOMAIN_NAME="default"
        OS_PROJECT_DOMAIN_NAME="Default"
        OS_COMPUTE_API_VERSION=2.37
        OS_NETWORK_API_VERSION=2.0
        OS_IMAGE_API_VERSION=2
        OS_VOLUME_API_VERSION=2
        OS_PRIVATE_NETWORK = "icp_network2"
        OS_NETWORK = "icp_network2"
	 }
    stages {
        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    env.OS_AUTH_URL = env.URL_SCNLPOWERCLOUD
                    sh '''
                    openstack image list --insecure --format value -c Name -c ID > images.scnlpowercloud.all.txt
                    for i in `cat images.scnlpowercloud.all.txt|awk '{print $2}'`; do line=$(grep $i images.scnlpowercloud.all.txt) ;  create_date=$(openstack image show $i --insecure | grep created_at | awk  'BEGIN{FS="|"}{print $3}' | sed 's/ *$//') ; echo -n  $line" " >> images.scnlpowercloud.all.date.txt; echo $create_date >> images.scnlpowercloud.all.date.txt ;done
                    cat images.scnlpowercloud.all.date.txt | sort -k3 -r > images.scnlpowercloud.all.date.sorted.txt
                    cat images.scnlpowercloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.6\\|cicd-rhcos-46' | awk '{print $2" "$1}'|head -n 1 > rhcos-4.6-powercloud-latest.txt || true
                    cat images.scnlpowercloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.7\\|cicd-rhcos-47' | awk '{print $2" "$1}'|head -n 1 > rhcos-4.7-powercloud-latest.txt || true
                    cat images.scnlpowercloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.8\\|cicd-rhcos-48' | awk '{print $2" "$1}'|head -n 1 > rhcos-4.8-powercloud-latest.txt || true
                    cat images.scnlpowercloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.9\\|cicd-rhcos-49' | awk '{print $2" "$1}'|head -n 1 > rhcos-4.9-powercloud-latest.txt || true

                    cat images.scnlpowercloud.all.date.sorted.txt | grep 'rhel8\\.2'  | awk '{print $2" "$1}'|head -n 1 > rhel-8.2-powercloud-latest.txt || true
                    cat images.scnlpowercloud.all.date.sorted.txt | grep 'rhel8\\.3'  | awk '{print $2" "$1}'|head -n 1 > rhel-8.3-powercloud-latest.txt || true
                    cat images.scnlpowercloud.all.date.sorted.txt | grep 'rhel8\\.4'  | awk '{print $2" "$1}'|head -n 1 > rhel-8.4-powercloud-latest.txt || true
                    '''
                    env.OS_AUTH_URL = env.URL_SCNLCICDPOWERVC
                    sh '''
                    openstack image list --insecure --format value -c Name -c ID > images.scnlcicdcloud.all.txt
                    for i in `cat images.scnlcicdcloud.all.txt|awk '{print $2}'`; do line=$(grep $i images.scnlcicdcloud.all.txt) ;  create_date=$(openstack image show $i --insecure | grep created_at | awk  'BEGIN{FS="|"}{print $3}' | sed 's/ *$//') ; echo -n  $line" " >> images.scnlcicdcloud.all.date.txt; echo $create_date >> images.scnlcicdcloud.all.date.txt ;done
                    cat images.scnlcicdcloud.all.date.txt | sort -k3 -r > images.scnlcicdcloud.all.date.sorted.txt
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.6\\|cicd-rhcos-46' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.6.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.7\\|cicd-rhcos-47' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.7.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.8\\|cicd-rhcos-48' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.8.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.9\\|cicd-rhcos-49' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.9.latest.txt || true

                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel8\\.2'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.2.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel8\\.3'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.3.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel8\\.4'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.4.latest.txt || true
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Pulling images failed !'
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("rhcos-4.6-powercloud-latest.txt", "rhcos-4.7-powercloud-latest.txt",
                                "rhcos-4.8-powercloud-latest.txt", "rhcos-4.9-powercloud-latest.txt",
                                "rhel-8.2-powercloud-latest.txt", "rhel-8.3-powercloud-latest.txt",
                                "rhel-8.4-powercloud-latest.txt", "cicd-rhcos-4.6.latest.txt", "cicd-rhcos-4.7.latest.txt",
                                "cicd-rhcos-4.8.latest.txt", "cicd-rhcos-4.9.latest.txt", "cicd-rhel-8.2.latest.txt",
                                "cicd-rhel-8.3.latest.txt", "cicd-rhel-8.4.latest.txt")
            cleanWs()
        }
    }
}
