@Library('pcloud-jenkins-library') _
pipeline {
    agent any
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
        OS_USERNAME = credentials('OS_USERNAME')
        OS_PASSWORD = credentials('OS_PASSWORD')
        PULL_SECRET = credentials('PULL_SECRET')
        URL_SCNLCICDCLOUD=credentials('URL_SCNLCICDCLOUD')
        URL_SCNLPOWERCLOUD=credentials('URL_SCNLPOWERCLOUD')

        VIR_CHOSE = "PowerVM"
        HARDWARE_CHOSE = "P9"
        NODE_OS = "rhcos-44"
        BASTION_OS  = "RHEL8.0"
        TIMEOUT = "0"
        RELEASE="4.4"

        FUNCTIONAL_TEST_REPO = "icp-sanity-bats"
        TERRAFORM_VER = "0.11.13"
        TEST_SUITE = "ppc64le-edge"
        OS = "linux"
        OS_IDENTITY_API_VERSION='3'
        OS_TENANT_NAME="ibm-default"
        OS_USER_DOMAIN_NAME="default"
        OS_PROJECT_DOMAIN_NAME="Default"
        OS_COMPUTE_API_VERSION=2.37
        OS_NETWORK_API_VERSION=2.0
        OS_IMAGE_API_VERSION=2
        OS_VOLUME_API_VERSION=2
        OS_PRIVATE_NETWORK = "icp_network2"
        OS_NETWORK = "icp_network2"
	 }
    stages {
        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    env.OS_AUTH_URL = env.URL_SCNLPOWERCLOUD
                    sh '''
                    openstack image list --insecure --format value -c Name > images.all.txt
                    for i in `cat images.all.txt`; do  create_date=$(openstack image show $i --insecure | grep created_at | awk  'BEGIN{FS="|"}{print $3}' | sed 's/ *$//') ; echo -n  $i" " >> images.all.date.txt; echo $create_date >> images.all.date.txt ;done
                    cat images.all.date.txt | sort -k2 -r > images.all.date.sorted.txt

                    cat images.all.date.sorted.txt| grep rhcos | awk '{print $1}' | grep '4\\.3\\|43' > rhcos-4.3.txt || true
                    cat images.all.date.sorted.txt| grep rhcos | awk '{print $1}' | grep '4\\.4\\|44' > rhcos-4.4.txt || true
                    cat images.all.date.sorted.txt| grep rhcos | awk '{print $1}' | grep '4\\.5\\|45' > rhcos-4.5.txt || true
                    cat images.all.date.sorted.txt| grep rhcos | awk '{print $1}' | grep '4\\.6\\|46' > rhcos-4.6.txt || true
                    cat images.all.date.sorted.txt| grep rhcos | awk '{print $1}' | grep '4\\.7\\|47' > rhcos-4.7.txt || true
                    cat images.all.date.sorted.txt| grep rhcos | awk '{print $1}' | grep '4\\.8\\|48' > rhcos-4.8.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep rhcos-43 | tail -n 1  > rhcos-4.3-nightly-latest.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep 'rhel8\\.0'  > rhel-8.0.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep 'rhel8\\.1'  > rhel-8.1.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep 'rhel8\\.2'  > rhel-8.2.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep 'rhel8\\.3'  > rhel-8.3.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep 'rhel7\\.6'  > rhel-7.6.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep 'rhel7\\.7'  > rhel-7.7.txt || true
                    cat images.all.date.sorted.txt| awk '{print $1}'| grep 'rhel7\\.8'  > rhel-7.8.txt || true
                    '''
                    env.OS_AUTH_URL = env.URL_SCNLCICDCLOUD
                    sh '''
                    openstack image list --insecure --format value -c Name -c ID > images.scnlcicdcloud.all.txt
                    for i in `cat images.scnlcicdcloud.all.txt|awk '{print $2}'`; do line=$(grep $i images.scnlcicdcloud.all.txt) ;  create_date=$(openstack image show $i --insecure | grep created_at | awk  'BEGIN{FS="|"}{print $3}' | sed 's/ *$//') ; echo -n  $line" " >> images.scnlcicdcloud.all.date.txt; echo $create_date >> images.scnlcicdcloud.all.date.txt ;done
                    cat images.scnlcicdcloud.all.date.txt | sort -k3 -r > images.scnlcicdcloud.all.date.sorted.txt

                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.3\\|cicd-rhcos-43' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.3.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.4\\|cicd-rhcos-44' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.4.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.5\\|cicd-rhcos-45' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.5.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.6\\|cicd-rhcos-46' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.6.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.7\\|cicd-rhcos-47' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.7.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'cicd-rhcos-4\\.8\\|cicd-rhcos-48' | awk '{print $2" "$1}'|head -n 1 > cicd-rhcos-4.8.latest.txt || true

                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel8\\.0'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.0.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel8\\.1'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.1.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel8\\.2'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.2.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel8\\.3'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-8.3.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel7\\.6'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-7.6.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel7\\.7'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-7.7.latest.txt || true
                    cat images.scnlcicdcloud.all.date.sorted.txt | grep 'rhel7\\.8'  | awk '{print $2" "$1}'|head -n 1 > cicd-rhel-7.8.latest.txt || true
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Pulling images failed !'
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("images.all.txt", "images.all.date.sorted.txt", "rhcos-4.3.txt", "rhcos-4.4.txt", "rhcos-4.5.txt",
                                "rhcos-4.6.txt", "rhcos-4.7.txt", "rhcos-4.8.txt", "cicd-rhcos-4.3.latest.txt", "cicd-rhcos-4.4.latest.txt",
                                "cicd-rhcos-4.5.latest.txt", "cicd-rhcos-4.6.latest.txt", "cicd-rhcos-4.7.latest.txt",
                                "cicd-rhcos-4.8.latest.txt",
                                "rhel-7.6.txt","rhel-7.7.txt", "rhel-7.8.txt","rhel-8.0.txt","rhel-8.1.txt",
                                "rhel-8.2.txt","rhel-8.3.txt","cicd-rhel-7.6.latest.txt","cicd-rhel-7.7.latest.txt",
                                "cicd-rhel-7.8.latest.txt", "cicd-rhel-8.0.latest.txt", "cicd-rhel-8.1.latest.txt",
                                "cicd-rhel-8.2.latest.txt", "cicd-rhel-8.3.latest.txt")
            cleanWs()
        }
    }
}
