@Library('pcloud-jenkins-library') _
//Define global variables
def AUTH_URL
def ZONE
def IMAGE
def MASTER
def WORKER
def MANAGER
def VA
env.DISTRO = ""

pipeline {
    agent {
        dockerfile {
            dir 'images/terraform'
            additionalBuildArgs '--force-rm	--no-cache'
            label 'daily-x86_64'
        }
    }
    triggers {
        cron('H H * * *')
    }
        environment {
            //users and credentials. All must be defined in Jenkins Credentials
            GITHUB_USER = credentials('GITHUB_USER')
            TF_VAR_user_name = credentials('GITHUB_USER')
            DOCKER_USER = credentials('DOCKER_USER')
            ARTIFACTORY_USER = credentials('ARTIFACTORY_USER')
            TF_VAR_repo_user = credentials('GITHUB_USER')
            TF_VAR_password = credentials('TF_VAR_password')
            OS_USERNAME = credentials('GITHUB_USER')
            OS_PASSWORD = credentials('TF_VAR_password')
            OS_INSECURE = true
            GITHUB_TOKEN = credentials('GITHUB_TOKEN')
            ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')

            //Env constants
            FUNCTIONAL_TEST_REPO = "icp-sanity-bats"
            TERRAFORM_VER = "0.11.13"
            TARGET = "deploy-power-powervc"
            TEST_SUITE = "ppc64le"
            OS_IDENTITY_API_VERSION='3'
            OS_TENANT_NAME="ibm-default"
            OS_USER_DOMAIN_NAME="default"

            VIR_CHOSE = "PowerVM"
            HARDWARE_CHOSE="P8"
            DISTRO_CHOSE = "RHEL7.6"
            DEPLOY_REPO = "daily"
            ICP_ADDITIONAL_CONFIG = ""
            SERVER_CONFIG = "Min"
            boolean SYSTEM_TUNING = false
            boolean DEPLOY_VA = false
            boolean DEPLOY_MANAGER = true
            boolean DEPLOY_WORKER = true
            TIMEOUT = "0"
            TERMPLATE_FILE = ".deploy-power-powervc.tfvars.template"

            //Removing carriage return from  ICP additional Configuration
            CONFIG=sh (returnStdout: true, script: "echo ${ICP_ADDITIONAL_CONFIG}|tr '\n' ' '")
            CONF = "'${CONFIG}'"
	 }

    stages {
        //Checkout the canary-deployment git repo
        stage('Clone Canary Deployment') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CheckoutOption', timeout: 60], [$class: 'CloneOption', depth: 0, noTags: false, reference: '', shallow: false, timeout: 60], [$class: 'RelativeTargetDirectory', relativeTargetDir: 'canary-deployments'], [$class: 'CleanBeforeCheckout']], submoduleCfg: [], userRemoteConfigs: [[ url: 'git@github.ibm.com:ICP-DevOps/canary-deployments.git', credentialsId: 'ibm-github']]])
            }
        }
        stage('Prepare Teraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {

                        echo 'Setting-up terraform template file for Max Config KVM!'
                        AUTH_URL=sh(returnStdout: true, script: "grep AUTH_URL conf/infra/pvm.conf|awk 'BEGIN{FS=\"AUTH_URL=\"}{print \$2}'|tr '\n' ' '").trim()
                        ZONE=getZone(env.VIR_CHOSE, HARDWARE_CHOSE )
                        if ("${ZONE}" == null)
                        {
                            echo "Requested zone could not find"
                            error('Requested zone could not find')
                        }
                        IMAGE=getTheImage(AUTH_URL, env.DISTRO_CHOSE )
                        if ("${IMAGE}" == "")
                        {
                            echo "Requested image could not find in ${AUTH_URL}"
                            error('Requested image could not find')

                        }
                        //16*8 > 128vcpus, 64G
                        MASTER=getTemplate(env.VIR_CHOSE, env.SERVER_CONFIG, "MASTER")
                        if ("${MASTER}" == null)
                        {
                            echo "Requested template could not find"
                            error('Requested zone could not find')
                        }
                        MANAGER=getTemplate(env.VIR_CHOSE, env.SERVER_CONFIG, "MANAGER")
                        WORKER=getTemplate(env.VIR_CHOSE, env.SERVER_CONFIG, "WORKER")
                        VA=getTemplate(env.VIR_CHOSE, env.SERVER_CONFIG, "VA")
                        // Updating tempate file with env variables
                        updateTemplate(AUTH_URL, ZONE, IMAGE, MASTER, WORKER, MANAGER, VA, env.DISTRO )
                        }
                    catch (err)
                    {
                        echo 'Error ! Template prepration failed !'
                        getArtifactoryAndClean(AUTH_URL)
                        throw err
                    }
                }
            }
        }
        stage('Initilize Environment') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''
                        echo 'Initializing supporting repos and keys !'

                        cd ${WORKSPACE}/canary-deployments
                        make init
                        make keys
                        make setup-dependencies
                        '''
                        }
                    catch (err) {
                        echo 'Error ! ENV setup failed!'
                        getArtifactoryAndClean(AUTH_URL)
                        throw err
                    }
                }
            }
        }
        stage('Deploy ICP Cluster') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''
                        echo 'Deploying Cluster!'

                        cd ${WORKSPACE}/canary-deployments
                        make $TARGET
                        sleep 60
                        '''
                        }
                    catch (err) {
                        echo 'Error ! Tearing off the cluster !'
                        getArtifactoryAndClean(AUTH_URL)
                        throw err
                    }
                }
            }
        }
        stage('Setup Kubectl') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''
                        echo 'Setting up the kubectl!'

                        cd ${WORKSPACE}/canary-deployments
                        make $TARGET:config
                        '''
                        }
                    catch (err) {
                        echo 'Error ! Tearing off the cluster !'
                        getArtifactoryAndClean(AUTH_URL)
                        throw err
                    }
                }
            }
        }
        stage('Run SERT Test') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''
                        echo 'Running SERT test!'
                        cd ${WORKSPACE}/canary-deployments

                        make run-functional-tests
                        '''
                        }
                    finally {
                        echo ' SERT Test Completed '
                        echo "HOLDING THE CLUSTER TEAR DOWN FOR ${TIMEOUT} SECONDS"
                        sleep TIMEOUT.toInteger()
                        getArtifactoryAndClean(AUTH_URL)
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts allowEmptyArchive: true, artifacts: 'canary-deployments/systeminfo.txt.tar.gz', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'canary-deployments/cluster.tar.gz', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'canary-deployments/cluster/config.yaml', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'canary-deployments/deploy-power-powervc.tfvars.template', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'canary-deployments/deploy-power-powervc.tfvars', fingerprint: true, onlyIfSuccessful: false
            cleanWs()
            notifyBySlack(currentBuild.result)
        }
    }
}