@Library('pcloud-jenkins-library') _
//Define global variables
env.DISTRO = ""
def TIMEOUT_SEC
def TIMEOUT_MIN
def TRIGGER
def BUILD
def E2E_SUMMARY

pipeline {
    agent {
        node {
            label 'daily-x86_64'
        }
    }
    triggers {
        cron('H * * * *')
    }
    stages {
        stage('Prepare Teraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r > builds.raw.txt
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r | awk '{print $1}' > builds.txt
                    for i in `cat builds.txt`;
                        do echo "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:$i" >> all-builds.txt;
                    done
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r | awk '{print $1}'| grep '^4\\.3' > builds.txt
                    for i in `cat builds.txt`;
                        do echo "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:$i" >> all-4.3-builds.txt;
                    done
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r | awk '{print $1}'| grep '^4\\.4' > builds.txt
                    for i in `cat builds.txt`;
                        do echo "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:$i" >> all-4.4-builds.txt;
                    done
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r | awk '{print $1}'| grep '^4\\.5' > builds.txt
                    for i in `cat builds.txt`;
                        do echo "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:$i" >> all-4.5-builds.txt;
                    done
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r | awk '{print $1}'| grep '^4\\.3' |  head -n 1 > builds.txt
                    for i in `cat builds.txt`;
                        do echo "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:$i" >> latest-4.3-build.txt;
                    done
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r | awk '{print $1}'| grep '^4\\.4' |  head -n 1 > builds.txt
                    for i in `cat builds.txt`;
                        do echo "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:$i" >> latest-4.4-build.txt;
                    done
                    curl https://openshift-release-ppc64le.svc.ci.openshift.org/ | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1' | grep "<td" | grep "href=" | sed 's/<\\/a//' |awk  'BEGIN{FS="href="}{print $2}' | awk 'BEGIN{FS=">"}{print $2} {print $5} {print $6}'|awk 'NR%3{printf "%s ",$0;next;}1'| sed 's/<\\/a//' | sed 's/<td title="//'|sed 's/\"//g' | sed 's/<\\/td//' | grep -v 'Failed' | sort -k3 -r | awk '{print $1}'| grep '^4\\.5' |  head -n 1 > builds.txt
                    for i in `cat builds.txt`;
                        do echo "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:$i" >> latest-4.5-build.txt;
                    done
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Template prepration failed !'
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts allowEmptyArchive: true, artifacts: 'builds.raw.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'all-builds.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'all-4.3-builds.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'all-4.4-builds.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'all-4.5-builds.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'latest-4.3-build.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'latest-4.4-build.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'latest-4.5-build.txt', fingerprint: true, onlyIfSuccessful: false
            cleanWs()
        }
    }
}
