@Library('pcloud-jenkins-library') _
//Define global variables
env.DISTRO = ""
def TIMEOUT_SEC
def TIMEOUT_MIN
def TRIGGER
def BUILD
def E2E_SUMMARY

pipeline {
    agent {
        dockerfile {
            dir 'images/poll'
            additionalBuildArgs '--force-rm	--no-cache'
            args '-v /etc/resolv.conf:/etc/resolv.conf'
            label 'daily-x86_64'
        }
    }
    triggers {
        cron('H H * * *')
    }
    stages {
        stage('Clone etcd code') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'quay_ws'], [$class: 'CleanBeforeCheckout']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/rpsene/ocp-build-of-the-day.git']]])
            }
        }
        //Checkout the installer git repo
        stage('pull artifact') {
            steps {
                script {
                    step([  $class: 'CopyArtifact',
                    filter: 'latest-4.3-build.txt',
                    fingerprintArtifacts: true,
                    projectName: '${JOB_NAME}',
                    target: 'old',
                    selector: lastSuccessful()
                    ])
                }
            }
        }
        stage('Prepare Teraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''
                    python3 quay_ws/ocp-build-of-the-day.py | sed -n -e '/Summary/,/----/ p' > all-builds.txt
                    python3 quay_ws/ocp-build-of-the-day.py -v 4.3.0 | sed -n -e '/Summary/,/----/ p' > all-4.3-builds.txt
                    python3 quay_ws/ocp-build-of-the-day.py -v 4.3.0 | sed -n -e '/Summary/,/----/ p' | grep -v 'Summary\\|---*' | tail -n 1 > latest-4.3-build.txt
                    python3 quay_ws/ocp-build-of-the-day.py -v 4.4.0 | sed -n -e '/Summary/,/----/ p' | grep -v 'Summary\\|---*' | tail -n 1 > latest-4.4-build.txt
                    python3 quay_ws/ocp-build-of-the-day.py -v 4.5.0 | sed -n -e '/Summary/,/----/ p' | grep -v 'Summary\\|---*' | tail -n 1 > latest-4.5-build.txt
                    if [ `diff -q latest-4.3-build.txt old/latest-4.3-build.txt | wc -l`  -eq 1 ]; then
                        echo "yes" > trigger.txt
                    else
                        echo "no" > trigger.txt
                    fi
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Template prepration failed !'
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts allowEmptyArchive: true, artifacts: 'all-builds.txt', fingerprint: true, onlyIfSuccessful: false
            archiveArtifacts allowEmptyArchive: true, artifacts: 'all-4.3-builds.txt', fingerprint: true, onlyIfSuccessful: false   
            archiveArtifacts allowEmptyArchive: true, artifacts: 'latest-4.3-build.txt', fingerprint: true, onlyIfSuccessful: false
            cleanWs()
            script {
                if ( env.OPENSHIFT_INSTALL_TARBALL == "null")
                {
                    env.OPENSHIFT_INSTALL_TARBALL = "No new build"
                }
            }
            //notifyBySlackOcp4(currentBuild.result, env.OPENSHIFT_INSTALL_TARBALL, E2E_SUMMARY)
        }
    }
}
